### ISSUE TITLE
Redirect to Article Page after Front End Editing

### ISSUE THREAD

**Issue by Mr-Anonymous** [getk2/k2-v3-dev-build#128]
I not sure if I had mentioned this before, but if I find it nearly impossible to return to the item page after using front-end editing. Is it possible to redirect user back to the article page when we click "Save & Close" in front-end editing?

**Comment by paulvanharen** [comment]
Fixed with https://github.com/getk2/k2-v3-dev-build/commit/99f2b7ca322a8fd3b910f2bb1dc0780d27f24cfa, https://github.com/getk2/k2-v3-dev-build/commit/1e949fc13db01d44be128078a7a495e161f95841 and https://github.com/getk2/k2-v3-dev-build/commit/61e573aa2e62201625a575c64df14411e2678ca2
