### ISSUE TITLE
Frontend New Item Link Auto Pre-selects Category

### ISSUE THREAD

**Issue by Mr-Anonymous** [getk2/k2-v3-dev-build#146]
Is it possible to make the frontend "K2_ADD_A_NEW_ITEM_IN_THIS_CATEGORY" button to auto-selects the category the button was clicked from? I mean, if I click this 'New Item' button from the 'cars' category, I would like the front-end editing screen's Category setting pre-selected with the 'cars' category.

**Comment by paulvanharen** [comment]
This is the same request as #222.
