### ISSUE TITLE
Images in Backend not shown

### ISSUE THREAD

**Issue by franz-wohlkoenig** [getk2/k2-v3-dev-build#148]
In Backend/Edit Item in Image-Tab are Images after Data-Migration not shown. In Network-Tab of Dev-Tools no Response.
![image-edititem-backend](https://cloud.githubusercontent.com/assets/8235763/5458989/3ec6ed86-8557-11e4-8b2c-bac7e24c3d4b.jpg)

Watching Items in new Image-Grid no Items are showen, Response also empty in Dev-Tools.
![image-grid](https://cloud.githubusercontent.com/assets/8235763/5458981/1cbc2a44-8557-11e4-89b7-abf22c85829a.jpg)

In List-Layout after Click on Image-Icon got Message "The image could not be loaded". In Network-Tab of Dev-Tools is an 404-Not found Message.

**Comment by paulvanharen** [comment]
Fixed along with fix of #297.
