### ISSUE TITLE
Multiple clicks on SAVE button

### ISSUE THREAD

**Issue by styleware** [getk2/k2-v3-dev-build#177]
Hi,
When you click multiple times on SAVE button more than one requests for synchronizations are sent.
As results there is TypeError: form.k2Plugins is undefined

There is no loss of information but it's a issue that's good to be fixed :)

Regards,
StyleWare

**Comment by paulvanharen** [comment]
@kavadas 
I could not reproduce this issue. Maybe my computer is too fast. Nevertheless, I propose to close the issue.
