### ISSUE TITLE
Tags ids conditions on SELECT doesn't work since some revisions.

### ISSUE THREAD

**Issue by visual74** [getk2/k2-v3-dev-build#185]
Hi,
Since my last update (rev. 1504), filter a items list by tag is unvailable.
On /administrator/components/com_k2/models/item.php line 312.
If I change :
`$query->leftJoin('('.$subquery->__toString().')` ..
by :
`$query->innerJoin('('.$subquery->__toString().')` ..

The filter works well. I don't know why It worked before my update, and not now..
Thank you.

**Comment by kavadas** [comment]
Hi,

Are you talking about the tag listing page? Or are you using custom code?

**Comment by visual74** [comment]
It is from custom select : 
`$model = K2Model::getInstance('Items')->setState('category', '5)->setState('state', 1)->setState('tag', 3);
 $model->getRows();`

**Comment by kavadas** [comment]
Ensure that the tag with ID 3 has not been deleted manually from your installation. What you report makes me thing that the tag entry ( #__k2_tags table ) has been deleted but the reference entry (#__k2_tags_xref table ) is still there.

**Comment by visual74** [comment]
No It's ok, I've got a tag with ID 3.
I see if I've got less than 50 relateds items by tags, the filter works good.
But more than 50, the filters doesn't work.

It's not broke since my last update, It's broke since I've got more than 50 relateds items.

**Comment by kavadas** [comment]
I suggest to enable Joomla! debugging to see if any query fails.

**Comment by visual74** [comment]
So I know where is the problem, and I'm sorry but It's in K2 Component I think :)
Please see /administrator/components/com_k2/models/item.php on line 294.

You've got two differents query for get related items by Tags :

```
[...]
else if ($numOfTaggedItems <= 50)
{
    if (!isset(self::$cache[$condition]['itemIds']))
    {
        $subquery = $db->getQuery(true);
        $subquery->select($db->quoteName('itemId'))->from($db->quoteName('#__k2_tags_xref'));
	$subquery->where($db->quoteName('tagId').' IN ('.$condition.')');
	$db->setQuery($subquery);
	self::$cache[$condition]['itemIds'] = $db->loadColumn();
    }
    $query->where($db->quoteName('item.id').' IN ('.implode(',', self::$cache[$condition]['itemIds']).')');
}
else
{
    $subquery = $db->getQuery(true);
    $subquery->select($db->quoteName('itemId'))->from($db->quoteName('#__k2_tags_xref'));
    $subquery->where($db->quoteName('tagId').' IN ('.$condition.')');
    $subquery->group($db->quoteName('itemId'));
    $query->leftJoin('('.$subquery->__toString().') AS '.$db->quoteName('xref').' ON '.$db->quoteName('item.id').' = '.$db->quoteName('xref.itemId'));
}
```
The first one is when the count of related items by tags is less than 50, the second is for more than 50

When I override $numOfTaggedItems = 40 (because normally I've got more than 50), the query/filter works well !
The first query, for less than 50 is ok, but not the second. And I don't want to override the K2 component..

Why a differente query if $numOfTaggedItems > 50 ?
If it's < 50, the returned list is filtered, but >50, the leftJoin return all items witout filters on tags! Same ask, different result.

I hope this is understandable. Thank you :)

**Comment by kavadas** [comment]
Can you apply this https://github.com/joomlaworks/k2-v3-dev-build/commit/e9c436a62a39f4b832f137727ff65e85e958a0e4 and verify that it works as it should?

**Comment by paulvanharen** [comment]
Solution proposed and nu feedback for over a year -> Item closed
