### ISSUE TITLE
Bug in add category after last commit

### ISSUE THREAD

**Issue by kewwel** [getk2/k2-v3-dev-build#197]
I downloaded the latest update and saw that there are bugs in the layout of the category description, let alone that does not save the category. I did these tests with clean joomla.

**Comment by kewwel** [comment]
I noticed that if you set CodeMirror as principal editor, you can not save anything on k2. Example: with it on, I set up the category. And do not save anything. Only closes.

**Comment by kavadas** [comment]
Hi,

Currently only TinyMCE and JCE are supported. Since K2 is written in javascript out of the context of Joomla! editors plugins it requires an editor with a javascript API.

**Comment by kewwel** [comment]
And if I do not want to use any editor, still bugged?
