### ISSUE TITLE
Display settings

### ISSUE THREAD

**Issue by Edward0625** [getk2/k2-v3-dev-build#211]
Hi,

in category "Other layout options" the "Item ordering" setting not work. From front-end not displayed what i am setting in back-end.
![image](https://cloud.githubusercontent.com/assets/7513278/6410261/0ed9c418-be6e-11e4-906a-8f54141c9e82.png)

For me in back-end now work everything, just this option no. Thank you!

**Comment by kavadas** [comment]
Hi,

We are aware of this issue, front-end is not completed yet. Thank you for reporting.
