### ISSUE TITLE
Hiding "'Featured' notice (next to title)" on Item Options doesn't work

### ISSUE THREAD

**Issue by iNarek** [getk2/k2-v3-dev-build#215]
(on Joomla 3.3.6)

**Comment by kavadas** [comment]
Hi, 
We are aware of this issue. The front-end is not finalized yet. Thanks for your feedback.

**Comment by paulvanharen** [comment]
I just checked and this issue and could not reproduce it. My take on it is, that this has been solved when completing the front end about one year ago.
