### ISSUE TITLE
Upgrade failed

### ISSUE THREAD

**Issue by drjjw** [getk2/k2-v3-dev-build#224]
Hello,

When installing today's master installer for K2v3 over top a 2.6.9 installation for Joomla 3.4, the upgrade of the previous installation failed. After seeming to convert all the items, categories, tags, the error in the popup simply said

Upgrade failed

It then restored my previous version.

Also, not sure whether related but on installation, received:

JFolder: :delete: Path is not a folder. Path: /Applications/MAMP/htdocs/ukx/components/com_k2/controllers

JFolder: :delete: Path is not a folder. Path: /Applications/MAMP/htdocs/ukx/components/com_k2/js

JFolder: :delete: Path is not a folder. Path: /Applications/MAMP/htdocs/ukx/components/com_k2/models

JFolder: :delete: Path is not a folder. Path: /Applications/MAMP/htdocs/ukx/components/com_k2/sef_ext

JFolder: :delete: Path is not a folder. Path: /Applications/MAMP/htdocs/ukx/administrator/components/com_k2/elements

JFolder: :delete: Path is not a folder. Path: /Applications/MAMP/htdocs/ukx/administrator/components/com_k2/jupgrade

JFolder: :delete: Path is not a folder. Path: /Applications/MAMP/htdocs/ukx/administrator/components/com_k2/lib

**Comment by kavadas** [comment]
Hi,

Are you sure that there was no other message than the "Upgrade failed" ? The rest messages there are warnings and can be ignored until we fix them.

**Comment by drjjw** [comment]
Hello,

No, there was no error message other than that. It failed with that simple
message and the previous installation was automatically restored.

Jordan

**Comment by paulvanharen** [comment]
This problem is solved along with the fix of #273
