### ISSUE TITLE
localize date picker

### ISSUE THREAD

**Issue by safajuy** [getk2/k2-v3-dev-build#228]
is not working with localize date picker in languages. for example jalali date picker

**Comment by paulvanharen** [comment]
I've been looking at the date picker and the potential localization. The date picker comes with a series of translation files, each implemented as executable jQuery scripts, see http://amsul.ca/pickadate.js/date/#translations. 
I'm now looking at two issues: 
*) the translation scripts need to be loaded; yet in the present date picker context that is not trivial
*) the translation scripts make references to jQuery's $ invokation directly, which is typically undefined in this context. 

A way out would be yet another date picker, that has a different localization implementation. There is another motivation to look at another date picker that is in the associated time picker functionality. The time picker generates first a list with all acceptable times and presents these in the a select box. In case you'd like minutes resolution for the entire day, you get a list of 24 x 60 options. There are other implementations that give 2 selection lists: one for hours and one for minutes, or that allow keyboard entry for the time to refine from a course list. 

My idea is to start looking for another date-time-picker. Yet, these are all dependent on multiple JS libraries and I can use some help for a proposal.

**Comment by kavadas** [comment]
Are there any suggestions for a different picker plugin?

Regarding the translation scripts, we could load and initialize the picker directly in administrator/components/com_k2/views/k2/view.html.php before the K2 application is initialized.

**Comment by paulvanharen** [comment]
I've been looking at http://eonasdan.github.io/bootstrap-datetimepicker/ or https://github.com/xdan/datetimepicker
