### ISSUE TITLE
Feature request: Disable JavaScript Parameter

### ISSUE THREAD

**Issue by heyjoecampbell** [getk2/k2-v3-dev-build#229]
Under "CSS & JavaScript Settings" add a parameter for "K2 default JavaScript" with same options provided for CSS "Disable" and "Enable".

The need to unset K2's JS is too complicated, especially since you have to include the version (which can be forgotten when upgrading <and> makes it impossible when using third-party script disablers)

http://www.joomlaworks.net/forum/k2-en/33253-how-to-unset-k2-js#116714

**Comment by fevangelou** [comment]
Paul, this is a breaking change. If people disable frontend JS loading of K2's minimal js code, this breaks many, many features in K2, e.g. comments posting, modals, frontend editing etc.

These things do not need to be overwritten.

**Comment by heyjoecampbell** [comment]
Some do not use any of these features:

- Disqus Comments
- Regular Labs Modals
- NO frontend editing

**Comment by fevangelou** [comment]
So? 2k is gonna break your site? You don't know what you're talking about.
