### ISSUE TITLE
Extra Field Dropdown List Order

### ISSUE THREAD

**Issue by heyjoecampbell** [getk2/k2-v3-dev-build#236]
Offering either a field to enter the value order and/or the ability to drag to rearrange the order of an Extra Field dropdown and multi-select list would be most helpful.

Why it this Important: because currently a site administrator would have to cut & paste each value into another value position BUT doing this would effect all items (as the value of the item is based on the dropdown & multi-select ID and not entered value)

Note: the order of the values of many dropdown & multi-select is often needed to present the values in a specific order for the end-user.

**Comment by paulvanharen** [comment]
Fixed as side effect of fixing #169
