### ISSUE TITLE
extraFields in categoryItem view generating invalid argument error

### ISSUE THREAD

**Issue by kbrookes** [getk2/k2-v3-dev-build#239]
'''
Warning: Invalid argument supplied for foreach() in /home/XXX/public_html/components/com_k2/templates/default/category_item.php on line 139
'''

Using the default template.

I have the Extra Field group scoped to the item and assigned to the category view option, and extra fields are turned on in both listings and items.

No errors on the item view and extra fields appear correctly.

Have ensured that the extrafields code on category_item.php is pulled from the current (as of writing) version on GitHub.

**Comment by kricore** [comment]
Hello there Kelsey and thank you for your feedback,

The front-end is not finalised yet. We are currently working on it.
Did you test my templates as well?

**Comment by kbrookes** [comment]
Hi Kricore,

The new extrafields code from itemlist_item does indeed work within the old category_item code.

The new default template doesn't seem to work at all in category view at the moment, so I'm currently creating 'frankentemplates' that are an unholy combination of v2 and v3.

BTW - I'm only really getting a glimpse of how awesome the new features are in the frontend templates. I know you won't have time at the moment, but I would love to see some more examples for the _inc folder - but also how to actually implement _inc. 

An example of what I'd like to see for extrafields would be a way to explode each 'entry' in a single extra field value into a foreach loop. I sometimes use extrafields to create classes for isotope filtering,  but I've never found a great way to do it, particularly when I have extrafield values that have two words.

**Comment by paulvanharen** [comment]
@kavadas 
I cannot reproduce this issue. I propose to close.
