### ISSUE TITLE
Multiple textarea extra fields used with editor 

### ISSUE THREAD

**Issue by markfran** [getk2/k2-v3-dev-build#242]
Hi,

first of all, thanks for the great work!
I found an issue while creating a extra field category which contains multiple textarea extra fields using  the WUSIWYG-Editor. 
If you apply the extra fields to an category and try to save the input in the extrafields, editing an item, you're not able to save the item.
If you have only no or a single editor, everything works fine. 

Looking forward to the next version

**Comment by paulvanharen** [comment]
Dear @markfran,

With the recent updates, editing multiple textarea extra fields should work according to expectation for TineMCE, JCE, CodeMIrror and none. Would you be so kind to verify that your problem is also gone now?

Thanks, Paul

**Comment by markfran** [comment]
Hallo, 

thank you for the reply.

I can confirm that part of the problem is solved. With the current version, I can now save changes to the textareas. But using the WUSIWYG-Editor all changes regarding the formatting and style are ignored. 

For example if I create a list, after saving the list is disappeared and only the text remains. 

Regards
Markus
