### ISSUE TITLE
Can't change menu item type after selected k2 categories

### ISSUE THREAD

**Issue by markfran** [getk2/k2-v3-dev-build#244]
I got stuck editing my menu bar after I created a new menu item and selected as menu item type k2 -> categories. Once I save any menu item as k2 -> categories I'm not able to change it in to something different because the dialogue is simply not showing up. The background gets dark, but nothing else happens (see image). 
The only way to change the item type is to delete the menu item an create a new one. 
<img width="1322" alt="bildschirmfoto 2015-09-18 um 14 02 23" src="https://cloud.githubusercontent.com/assets/5844759/9958853/3a3138cc-5e0e-11e5-84e5-10605203c456.png">

**Comment by kavadas** [comment]
The issue is probably by the k2.css file which is loaded in K2 menu links. I see a rule at line 34 that probably breaks that.

**Comment by paulvanharen** [comment]
@kricore 
I can confirm kavadas' suspicion. Disabling line 34 in k2.css removes this problem.
