### ISSUE TITLE
No introtext word limit for search, user, and tags views?

### ISSUE THREAD

**Issue by kbrookes** [getk2/k2-v3-dev-build#252]
Just wondering if there's another way to deal with this?

**Comment by kavadas** [comment]
We are already aware of this issue. Front-end is not completed yet. Thanks for reporting.

**Comment by kbrookes** [comment]
Thanks - I don't think I was clear that these options aren't available in the K2 admin settings.

**Comment by kavadas** [comment]
Yes, the parts that need to finalized are the options and the front-end.
