### ISSUE TITLE
Ordering has no effect

### ISSUE THREAD

**Issue by markfran** [getk2/k2-v3-dev-build#258]
Hi, 
I found a bug in the ordering. 
I created a category and added a couple of items in the backend. I set my own order for the items, by selecting the ordering view and tracked the items to the right place. Doesn't matter which item ordering type I select, the items are always displayed in the same order. 
Regards

**Comment by kbrookes** [comment]
I can confirm - I had to use the unfinished frontend templates from Krikor to manually set ordering in the template.
