### ISSUE TITLE
Can't set a custom create/publish date with keyboard entry

### ISSUE THREAD

**Issue by kbrookes** [getk2/k2-v3-dev-build#264]
While I like the fancy new date picker on an item's create/published/finish field, when you need to set a custom date that's not near the current date it's a major pain in the bum.

My current project I'm migrating a bunch of articles from a Wordpress site. I first imported to Joomla com_content, then used the K2 migration utility. Most, but not all came through just fine. A few didn't make it across from com_content to K2 and I needed to do them manually. Those new ones needed to be set to created/published dates far in the past.

It was a major, major pain to have to click back through the months to 2009 to set the dates - it'd be great to be able to do it via text entry as well, as it is in the 2.X series.

**Comment by kavadas** [comment]
Can you provide details regarding the articles that didn't import? Did you get a failure message during the import process?

**Comment by kbrookes** [comment]
No failure messages and I couldn't see any pattern - they were all 'blog' posts with an image. It was only about four in 200ish articles, so not a massive issue.

If I go through the process again at any point I'll pay more attention.
