### ISSUE TITLE
Can't submit comments with NoCaptcha

### ISSUE THREAD

**Issue by kbrookes** [getk2/k2-v3-dev-build#267]
With Google NoCaptcha enabled, the form and the 'I am not a robot' appear, but the process fails.

The initial click on the 'submit' button does nothing.

A second click results in the following error:

https://www.dropbox.com/s/bvpqrgwwh8jm1qt/Screenshot%202015-10-08%2008.00.52.png?dl=0

I have Recaptcha enabled in global settings:

https://www.dropbox.com/s/9bepbyhalb8iy6l/Screenshot%202015-10-08%2008.05.00.png?dl=0

**Comment by kavadas** [comment]
This is the response from the Google NoCaptcha not from K2. Have you entered the required keys for the service? They can be found at the "Antispam" section in the settings page. Can you also try from a different browser/computer?

**Comment by kbrookes** [comment]
I have definitely added the keys into the anti-spam section (I double checked against the keys for rsform pro and joomla core account creation) and I've just tested it in different browsers on the same computer and on different computers.

Same response - first click is unresponsive, second generates the error.

**Comment by kavadas** [comment]
@kbrookes 

Just tested and it works fine for me. Can you please check again? Grab a fresh copy and let me know.

**Comment by paulvanharen** [comment]
I double checked and Google reCaptcha works fine for me.
