### ISSUE TITLE
modpagespeed backend

### ISSUE THREAD

**Issue by Twincarb** [getk2/k2-v3-dev-build#269]
With the latest update to mod Pagespeed  the interface in the backend doesn't display and just waits about waiting forever, I had forgotten it was enabled on the server I am testing it on. So up until now it has played well with mod pagespeed.

![k2errer](https://cloud.githubusercontent.com/assets/14825222/10417736/0b37f8fc-703e-11e5-83ae-78087b9abee7.jpg)

**Comment by kavadas** [comment]
Can you check the browser console for any errors?

**Comment by Twincarb** [comment]
Morning Kavadas,
There is one error showing which is below.
![untitled-1](https://cloud.githubusercontent.com/assets/14825222/10425508/0c6758b6-70d0-11e5-8e12-98b6dac0a678.jpg)

**Comment by kavadas** [comment]
Are you using a fresh copy of the extension? Can you verify that this is related with Pagespeed module? Does it work if you disable it?

**Comment by Twincarb** [comment]
The site I am having this issue on is a fresh joomla install with K2 V3 installed on it, with the domain setup with pagespeed on I get the error above and the screen shot as previously. When I explicitly turn off pagespeed on the domain it works normally.
As I said originally the only software that had changed was the updated pagespeed on the server

**Comment by paulvanharen** [comment]
I tried to reproduce the above problem using pkg_mspagespeed-free-3.5.1.zip, and verified the functionality in Chrome and FireFox. I could not reproduce the issue.
