### ISSUE TITLE
Content lost after upgrade

### ISSUE THREAD

**Issue by paulvanharen** [getk2/k2-v3-dev-build#273]
Trying to reproduce issues #266 and #259, I found that I lost the content previously contained in K2 v 2.6.9.

The steps I took: a fresh Joomla installation with a fresh K2 v 2.6.9. I then created a category and an article. Everything is looking okay. Then I upgrade using k2-v3-dev-build-master.zip from Github, which seems to be okay. I only get some warnings that some directories cannot be removed as these do not exists.

However, all content is gone. Looking into my database I see that the former k2 tables are now renamed into k2_v2 and that new (empty) k2 tables are created. From the installation code (script.k2.php) this is clear, as it seems to be coded this way, i.e. the code is straight forward and does exactly this. 

Question: what is the way forward? Is there a complex data shuffle needed, backing up the old data in the old tables (relabelled to k2_v2), and then transferring all data back to the new tables? Or is the right way forward to upgrade and modify the tables to the latest status without changing the table names?

Please advise.

Regards, Paul

**Comment by kavadas** [comment]
Hi,

Have you run the migration process? Did it complete successfully? Did you get any other messages? 
K2 has to import all content from 2.x version to the new tables. That's why the old tables are renamed. This also allows us to roll back to K2 2.x in case the migration fails.

**Comment by paulvanharen** [comment]
Dear @kavadas,

I checked more carefully today.  I had a few warnings - which I ignored for the time being:
> Warning
> JFolder: :delete: Path is not a folder. Path: /home/web/k2/components/com_k2/controllers
> JFolder: :delete: Path is not a folder. Path: /home/web/k2/components/com_k2/js
> JFolder: :delete: Path is not a folder. Path: /home/web/k2/components/com_k2/models
> JFolder: :delete: Path is not a folder. Path: /home/web/k2/components/com_k2/sef_ext
> JFolder: :delete: Path is not a folder. Path: /home/web/k2/administrator/components/com_k2/elements
>JFolder: :delete: Path is not a folder. Path: /home/web/k2/administrator/components/com_k2/jupgrade
>JFolder: :delete: Path is not a folder. Path: /home/web/k2/administrator/components/com_k2/lib

As a result, the migration button was shifted down below the fold and I overlooked it. Now I know where to look, I pressed the button and everything is okay. 

Another entry with the same button in the K2->utilities tab maybe beneficial.

Best regards, Paul
