### ISSUE TITLE
Add More Views/Options to K2 Stats (Admin)

### ISSUE THREAD

**Issue by heyjoecampbell** [getk2/k2-v3-dev-build#277]
Add more views:
- Latest Modified
- Latest Published

**Comment by kricore** [comment]
I think an extension would provide better integration.
Eg: Offer Google analytics integration and display the most popular, integration with other analytics services.

**Comment by heyjoecampbell** [comment]
Not really, Google Analytics would not know your backend vitals.

I am merely saying, if you are working on two specific items, when you log back into your Joomla backend, you should be able to see and with one click navigate to the item edit page for those recently modified items.

Also, it would be ideal to see a snapshot of your items that were recently published. This would be most helpful for those who schedule items in advance.
