### ISSUE TITLE
Bring it live :)

### ISSUE THREAD

**Issue by Robdebert** [getk2/k2-v3-dev-build#281]
Sorry to post this as an issue, i didn't find any comment-form or board to post this.

The article http://getk2.org/blog/2073-first-beta-of-k2-version-3-is-here is from 2014. 
The latest changes here are over 3 and 5 months old, the others even older than 1 year.

When can K2 v3 come out as stable? Do you need any help from PHP-developers?

**Comment by Mr-Anonymous** [comment]
It will be live when we have flying cars! :)

**Comment by paulvanharen** [comment]
@Robdebert 
We're in the process of revitalizing the K2 v3 developments. We still have quite some work ahead, and yes progress has been slow. 

K2 is an open source development activity. In case you want to contribute to this development as PHP-developer or for testing the current versions, please make yourself known. 

More discussions on the progress on K2 v3 can be found on the JoomlaWorks forum http://www.joomlaworks.net/forum/k2-en/40480-what-happened-to-k2-3-0. 

As part of the clean up for this issue log, I'd like to close this topic here.
