### ISSUE TITLE
Joomla native tags integration

### ISSUE THREAD

**Issue by progettowebfirenze** [getk2/k2-v3-dev-build#283]
Provide a way to integrate with standard Joomla tags.

**Comment by kavadas** [comment]
Hi,

May i ask what's the reason for it? I mean K2 has already it's own tags implementation. Is there something that you think it's handled in a better way in the core tags?

**Comment by progettowebfirenze** [comment]
Of course it has... but i find much more usefull if compèonents fully integrate also with native tag system.
Imagine an installation with
content
k2
events
virtuemart

each with a different tagging system..
It's a real mess. Much better to use just one...

**Comment by kavadas** [comment]
I totally disagree with this but i will mark it as an enhancement so the rest of the team can review it at the future.

**Comment by fevangelou** [comment]
Joomla tags are to be avoided. It's a mess, sorry. Whatever you wanna do with K2 tags is already provided by K2. Would you ever want to retrieve a tag listing from K2 items and Joomla articles? If you did, you either wouldn't use K2 (cause com_content would be sufficient) or you wouldn't use com_content. Plus Joomla tags suck from a performance stand point. K2 bets seriously on performance.

**Comment by progettowebfirenze** [comment]
I want to retrieve tags from K2, com_content, virtuemart and other components without having to write a custom component just to get a simple query..
Ok... i'll do myself.

**Comment by fevangelou** [comment]
When content is different as "entities", there is no point in combining views. It's also the performance perspective. This decision is not to piss you off (or anyone else for that matter), it's design by convention. We have to keep some simple rules. That's all.

Of course if you have the know how, creating a custom view as you mentioned should not be difficult.
