### ISSUE TITLE
Migration failed - all items lost

### ISSUE THREAD

**Issue by drjjw** [getk2/k2-v3-dev-build#284]
Migration from K2 2.6.9 to 3 failed (again). Hangs on

Processing Tags Reference
100%

FWIW, JS error in console:

JQMIGRATE: Logging is active
jquery.js:358 Uncaught TypeError: Cannot read property 'length' of undefined

If I go to K2, all categories and tags migrated. All items but one (of 390) are gone.

Jordan
Joomla 3.4.8
PHP 5.6

**Comment by paulvanharen** [comment]
Dear @drjjw,

I found and fixed some issues with the progress indicator. I've tested the migration on a copy of one of my production sites (8000 articles) and this all looks fine. 

Would you be so kind to verify whether this makes the difference at your end too?

Thanks and regards, Paul

**Comment by drjjw** [comment]
Hi again,

It made a difference in that I progressed to:

Processing Tags Reference
100%

Nothing further happened after that and, gain, all but one K2 item imported. All else lost. No errors thrown.

Admittedly, this is a mature Joomla site with other extensions installed which might be conflicting, though I imagine this will be true of many people and there will might be migration issues on large scale.

Jordan

**Comment by paulvanharen** [comment]
Would it be possible to have a copy of your website, or a subset, for further analysis?
