### ISSUE TITLE
Error when clicked in "Add"

### ISSUE THREAD

**Issue by AlmeidaLeonardo** [getk2/k2-v3-dev-build#288]
When I access the K2 he open the items list.
That's fine, but when clicked in "Add", he appear that red message.
I install the K2 on localhost if help in something.
I insert the Joomla info (Apache, PHP, Joomla, etc.)

![error](https://cloud.githubusercontent.com/assets/14799636/13826445/6015e23e-eb96-11e5-9700-7631bd06e57f.JPG)

![error02](https://cloud.githubusercontent.com/assets/14799636/13826545/e0649dfe-eb96-11e5-80d8-a1b407fa4399.JPG)

**Comment by kavadas** [comment]
Hi,

Can you examine the request that is made to the server? You can do this by using your browser's developer tools.

**Comment by AlmeidaLeonardo** [comment]
What tool do you recommend?

**Comment by kavadas** [comment]
Forget the developer tools, try to open this URL to your browser while you are logged in the administration area: administrator/index.php?option=com_k2&task=items.sync&format=json&id=null . 

The response should be valid JSON. You can validate this at http://jsonlint.com/ or just paste the response here so i can have a look.

**Comment by paulvanharen** [comment]
Error is no longer reproducible.
