### ISSUE TITLE
Option to override the template at item level 

### ISSUE THREAD

**Issue by creativeprogramming** [getk2/k2-v3-dev-build#291]
It would be nice for me to have an option that enables us to override the item template for any single item (I mean a dropdown selector for the template, like it's done now in the category settings, but of course affecting just the single item view ( item.php ) in this case.

Some use cases? 

- A sponsor post in a normal category may need a custom template e.g. to disable third party ads or simply to add a 'sponsor post' badge
- Offer a simple way for authors to change the main image layout (e.g. centered, floated left, floated right etc.) or the extra fields position (top, bottom...)

**Comment by paulvanharen** [comment]
Dear Stefano, 

You can implement such behavior easily with template overrides https://getk2.org/documentation/tutorials/174-templating-with-k2-and-the-concepts-of-sub-templates in conbination with the use of extra fields. 

Regards, Paul
