### ISSUE TITLE
Tags with more content

### ISSUE THREAD

**Issue by kewwel** [getk2/k2-v3-dev-build#292]
It would be interesting if the tags could have description, image, video and image gallery. With these implements would improve SEO and could use the tags as secondary categories. An example: Lionel Messi mark his 100th goal for Barcelona in the Spanish league.
We could use the category as football and then classify as Tags: Lionel Messi, Barcelona and La Liga.

This style is already used by Globo.com, most visited site in Brazil.
http://globoesporte.globo.com/atleta/messi.html
http://ego.globo.com/famosos/tudo-sobre/mayra-cardi.html

**Comment by paulvanharen** [comment]
Hi @kewwel, I think that in K2 the extra fields are the mechanism to use for this purpose. Please consider this as the alternative.

**Comment by kewwel** [comment]
I believe you do not understand me.
Because to use extra fields (with the job of creating one by one, set up in each category used) and you can use very well the tags?
My idea is that the tags have more content, and improve the seo as well.

As the tags have list, it would be very interesting this implement. It is much easier to label you an article about Michael Jackson in the category of news than having to create a category called Michael Jackson.

**Comment by paulvanharen** [comment]
What you're asking for is 'description, image, video and gallery'. To me that sounds like an item/article already and you're want to use the tag as a system wide shortcut to such an article.

**Comment by kewwel** [comment]
Theoretically it is nearly so. Tags having complementary articles. However this improvement, would serve to add more relevant content. I informed you two links that show that my idea. One of implements which more charge is to k2 is the multi categories scheme. With the improvement of advanced tags, you solve it, and let your most complete design for SEO. It is better you put a tag that has image, description of something with nothing.
I can only create a category called Barcelona and every article I have Messi, Suarez, Neymar and other players, I put them as tags. Easy, fast and objective.
