### ISSUE TITLE
Image Uploading not working

### ISSUE THREAD

**Issue by williamconifer** [getk2/k2-v3-dev-build#297]
greetings. 

I have today's K2 Ver 3 Dev. installed on a fresh Joomla 3.4.8. Running RocketTheme "Intersteller" which is using Gantry 5. The only other non Rockettheme plugin installed is JCE Editor. PHP 5.5.33

From the backend, I am not able to add a K2 photo in an item. This means using the Image tab in the edit Item form. When I click on Upload Image, I select the image and click select/open button. Nothing visibly happens. 

However the image is getting uploaded and resized and stored in the tmp folder. Here is the response I get get from Developer Tools {"temp":"570af230622e9","preview":"\/tmp\/570af230622e9\/cache\/570af230622e9_XS.jpg"} When I view my file system I see all the correct image versions sitting in the /temp folder NOT /media/k2/items/ folder. It's like the images are NOT getting copied over to the media folder.

**Comment by kavadas** [comment]
Hi,

Check the browser console for any errors.

**Comment by williamconifer** [comment]
Chrome console showing no errors. Firefox console is showing the following warning: 11:36:29.906 Empty string passed to getElementById().1 jquery.min.js:2:24487

**Comment by williamconifer** [comment]
Hey I corrected an important typo at the end of my first post. Now it correctly reads "It's like the images are NOT getting copied over to the media folder."

**Comment by txesko** [comment]
Confirmed... not working, the images is in temp folder, but not in media/k2/item/cache.
