### ISSUE TITLE
List/bulk operation buttons don't show

### ISSUE THREAD

**Issue by paulvanharen** [getk2/k2-v3-dev-build#298]
When selecting an article or category in the corresponding list, a toolbar with bulk operations should appear. Unfortunately, it doesn't always do so. This seems to be dependent on the server.

I took a fresh install of k2 v3 on a fresh Joomla 3.5.1. I created a single category and a single article. When selecting the article, the placeholder for the toolbar appears, but all buttons remain absent. In the HTML code, the <ul class="text-center jw--toolbar--actions"> remains an empty list. With the same browser pointing at getk2 development site, the list is properly filled. There are no obvious fields missing in the JSON output; all buttons seem to be present, or at least equivalent to the corresponding output on the getk2 development server.

The issue is reproducible on Chrome as well as on Firefox. My testserver is running Ubuntu 14.04 LTS; there are no significant configuration differences with the getk2 development server, other than the webserver itself (Apache ns Ngix).

**Comment by stimpsonjcat** [comment]
I can confirm there's no toolbar to (bulk) delete or on publish articles. This is a serious issue that should be fixed.
