### ISSUE TITLE
Errors when clicking Add under Categories tab

### ISSUE THREAD

**Issue by Simon-Davies** [getk2/k2-v3-dev-build#304]
Warning[2] Illegal string offset 'id'. Line 67 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Warning[2] Invalid argument supplied for foreach(). Line 46 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Categories: id. Line 98 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Notice[8] Undefined property: K2Categories::$image. Line 484 in file /home1/engetsui/public_html/administrator/components/com_k2/helpers/images.php
 Uknown error type[1024] Undefined property: K2Categories: title. Line 98 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Warning[2] Illegal string offset 'id'. Line 74 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Notice[8] Undefined property: stdClass::$catExtraFieldGroups. Line 176 in file /home1/engetsui/public_html/administrator/components/com_k2/views/categories/view.json.php

**Comment by paulvanharen** [comment]
Error is no longer reproducible.
