### ISSUE TITLE
Remove "#" Added Before K2 Tags

### ISSUE THREAD

**Issue by heyjoecampbell** [getk2/k2-v3-dev-build#305]
Please consider removing this from future releases, as it is imposing a style element onto K2 users, which can be especially problematic for those with minimal CSS experience.

Even more, I do not think it makes much sense when applied to multiword tags, as hashtags do not have spaces :)

**Comment by mabdelaziz77** [comment]
I agree with Joe, without "#" is better, at least make it configurable to enable/disable it.

**Comment by paulvanharen** [comment]
Hey Joe, can you help me here? What do you mean? In the front-end, I can find a list of tags per K2 item, but these are all in a simple unordered list '<ul class="itemTags">'. 

Best regards, Paul

**Comment by heyjoecampbell** [comment]
@paulvanharen I do not think K2 should be styling tags by default. 

@mabdelaziz77 wrote an article on his site to show people how to remove the pound symbol added to tags:
http://www.joomreem.com/joomla-resources/remove-hash-k2-tags#.V-mLnPkrLIU

For simplicity sake, this feature should be removed and added as a K2 Tip on the forum or blog to show people how to style K2 Tags :)

**Comment by paulvanharen** [comment]
Okay, so you're referring to HTML tags and not to article tags. Hmm, sounds like we're using ambiguous names here.

**Comment by heyjoecampbell** [comment]
My apologies for the confusion.

Do you agree with my suggestion?

**Comment by paulories** [comment]
#tag , on view.

that`s the problem?

I saw that on my projects. On css, have an content="" on item:before


Paulo RIES
61 99985.8591 (VIVO) - 61 99372.4759 (Claro) - @paulories
<http://www.twitter.com/paulories>
--
Trídia Criação e Desenvolvimento de Software LTDA
61 3039.3728 / http://www.tridiacriacao.com
TW: @tridiacriacao <http://www.twitter.com/tridiacriacao>
FB: Trídia Criação
<http://www.facebook.com/pages/Tr%C3%ADdia-Cria%C3%A7%C3%A3o/110612755714685>
--
JoomleirosBR + Joomla Calango/DF (http://www.joomlacalango.org)
<http://groups.google.com/group/jugbra-organizadores>

2016-09-27 10:01 GMT-03:00 Joe Campbell <notifications@github.com>:

**Comment by paulvanharen** [comment]
Hey Joe, I've looked at the examples in link in the article http://www.joomreem.com/joomla-resources/remove-hash-k2-tags#.V-mLnPkrLIU. I could not find any equivalent in the k2v3 css. Can you help me out here and point me to an example?

**Comment by heyjoecampbell** [comment]
My apologies - I am assumed it was baked in to K2v3 since it a default feature of 2.7

**Comment by fevangelou** [comment]
All this fuzz for a) the wrong version of K2 and b) something so simple to override...

https://github.com/getk2/k2/blob/master/components/com_k2/css/k2.css#L276

The hashtag symbol is a design choice and we don't plan on removing it from K2 v2 and it will make its way in v3 as well as it's something people are nowadays accustomed to (which is a convention btw)...

**Comment by heyjoecampbell** [comment]
Yes, easy to override, but the point is  a user should not need to do this. 

K2 should not be styling elements like this, as it can effect usability. 
Tags are not hashtags, especially when multiple words.

**Comment by fevangelou** [comment]
That's your opinion.
