### ISSUE TITLE
After upgrading K2 v3

### ISSUE THREAD

**Issue by SimonWayne** [getk2/k2-v3-dev-build#46]
Hello,

after upgrading K2 v2.6.8 > V3 all Items and Categories were deleted.

**Comment by paulvanharen** [comment]
The Warning messages take so much screen space that the migrate buttons are no longer visible on the installation screen. After fixing #273 the warnings are no longer there and the migrate button is available. I assume that this also fixes this issue. 

If not, please create a new issue report.
